spring:
  application:
    name: web-mvc-test
  datasource:
    url: jsbc:mysql://localhost:3307/fastsns?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: fastcampus
  data:
    redis:
      host: 127.0.0.1
      port: 6379

server:
  port: 9000
  tomcat:
    max-connections: 10000
    accept-count: 1000
    threads:
      max: 3000
      min-spare: 1000

logging:
  level:
    root: info